### ISSUE TITLE
`num` with array input

### ISSUE THREAD

**Issue by tshort** [Mc-Zen/zero#14]
I don't think that `num` with array input works in v0.3.0. The following example works in v0.2.0. In v0.3.0, I get: Dictionary does not contain key "prefix".

```typ
#import "@preview/zero:0.3.0": num
#context {
  let a = num(("8.8","100"))
  stack(..a)
}
```

I also have a feature request related to this. I'd be great if the result of `num` with array contents was aligned, meaning if you stack them or put them in a grid or table, they would align correctly like ztable. That'd make it easier for package authors to use zero.

As part of [tblr](https://github.com/tshort/tblr), I've implemented my own version of decimal alignment [here](https://github.com/tshort/tblr/blob/7ee2f7b25d52ad7282255a9d8f34cd41665a28e1/tblr.typ#L413) that does that, but I'd like an easier way to use zero's num.

**Comment by Mc-Zen** [comment]
Hi @tshort 

> I don't think that num with array input works in v0.3.0. The following example works in v0.2.0. In v0.3.0, I get: Dictionary does not contain key "prefix".

Oh indeed. I've already submitted version 0.3.1 but it hasn't been merged yet so I was just able to push a hotfix!

**Comment by Mc-Zen** [comment]
> I also have a feature request related to this. I'd be great if the result of num with array contents was aligned, meaning if you stack them or put them in a grid or table, they would align correctly like ztable. That'd make it easier for package authors to use zero.

The way that zero implements alignment is via a `show` rule for `table` and `table.cell` so this wouldn't work straightaway. For your case, do you mean just one column at a time? 

The ability to pass an array of numbers is actually more of a dirty solution to get some performance gains and it will be removed in the future. Let me shortly lay out why. 
1. We don't yet have user-defined types (elements) available that can be subjected to `set` and `show` rules. 
2. As a workaround, everyone uses `state`. 
3. But `state` is really bad and comes with a high performance cost. 
4. If you know you'll apply the same number settings to a series of numbers, you can just call `state.get()` once - this is what the `array` input version does. 
5.  As soon as `num` becomes a type, it can just return "content" and array return types are not possible anymore. 

What you can also do with the new version (since 0.3.1) is to pass the `num-state` itself to `num`. That is what `zero.ztable` now does. As an example:
```typ
#context {
  let state = zero.num-state.get()
  num("2.3e3222", state: state)
  num("332.3e3222", state: state)
}
```
This way you can also prevent repeated `state.get()` calls to happen. 

That being said, we could add some completely unrelated and new `zero.align-column()` function that takes a few numbers and all aligns them as `zero.ztable` does. It would return an array of content (all with the same width) that you could insert into any table, grid or stack.

**Comment by tshort** [comment]
Thanks for the background and details, @Mc-Zen. I'm closing this as a see you've fixed the bug.

For my needs, I really like the "add some completely unrelated and new zero.align-column()" idea you mentioned. I'm looking to align individual columns or column subsets. Right now, I'd effectively have to recreate `ztable` which I don't want to do.

**Comment by Mc-Zen** [comment]
> Right now, I'd effectively have to recreate ztable which I don't want to do.

On what you could not do is to call into `zero.ztable`? I don't know how `tblr` works but I assume you use the normal table function in the implementation. You can't just substitute this with the zero version?

**Comment by tshort** [comment]
`tblr` has an option to specify the table function. See the following example with `ztable`:

https://github.com/tshort/tblr/blob/master/examples/population-2.typ

That works and is useful. The main problem is that if the user applies text formatting to cells, that breaks alignment. It works better if I can apply the formatting prior to alignment.

**Comment by Mc-Zen** [comment]
Ah, I see. Can you give an example where it breaks alignment? There was an issue with something related which was fixed in `0.3.1`, so maybe it works now.

**Comment by tshort** [comment]
Here's a simple example where `strong` breaks alignment.

```typ
#import "@preview/zero:0.3.1":ztable

#ztable(columns: 1, format: (auto,),
[1.2345], [*100.*]
)
```

If formatting is applied after, then alignment works (but I want to do that at the cell level):

```typ
#strong(ztable(columns: 1, format: (auto,),
[1.2345], [100.]
))
```

**Comment by tshort** [comment]
Another idea might be to have an option for `num` to return it's components split up for alignment. I fooled around with that approach a bit. 

```typ
#import "@preview/zero:0.3.1": num

#let default-state = (
  digits: auto,
  fixed: none,
  product: sym.times,
  decimal-separator: ".",
  tight: false,
  omit-unity-mantissa: false,
  positive-sign: false,
  positive-sign-exponent: false,
  base: 10,
  uncertainty-mode: "separate",
  math: true,
  group: (
    size: 3, 
    separator: sym.space.thin,
    threshold: 5
  ),
  round: (
    mode: none,
    precision: 2,
    pad: true,
    direction: "nearest",
  )
)


#let a = ("1.23", "987", "45.").map(x => num(str(x), state: default-state))

#grid(columns: 3, align: (right,right,left),..a.map(x => x.body.fields().children).flatten())
```
