### ISSUE TITLE
Incorrect Digit Grouping with Currency Symbols in Zero Tables

### ISSUE THREAD

**Issue by pedrojvaz** [Mc-Zen/zero#7]
Hello,

I’ve encountered an issue with the Zero package in Typst. It appears that the package is treating currency symbols as digits, which results in incorrect digit grouping. For example, the amount **€121.00** is being formatted as **€,121.00**.

**Steps to Reproduce:**

1. Create a Zero table in Typst 
![image](https://github.com/user-attachments/assets/856b8525-398b-4e5e-94bd-bc0bf1d84397)
1. Add a currency value, such as €121.00
1. Observe the incorrect digit grouping in the output
![image](https://github.com/user-attachments/assets/bf8ee5d2-11d4-4da7-bb83-de23931eeb77)

**Expected Behavior:** The currency symbol should not be considered a digit, and the amount should be displayed correctly as **€121.00**.

**Actual Behavior:** The currency symbol is treated as a digit, resulting in the incorrect format **€,121.00**

Thanks

**Comment by Mc-Zen** [comment]
I think, what would be needed is some sort of "protected" content that you can insert into a cell which will be ignored for the number recognition. 

If we just made certain characters like the € symbol not be treated as a digit, the cell would be ignored altogether for number formatting. This is because currently, we only have:
- (entire) cell content is a number
- or not.

I believe that something like
```typ
#table(
   ...
  [#zero.nonum[€]121.00]
)
```
could be a good and general solution that will allow also for inserting for example footnotes into a numbered cell.
