### ISSUE TITLE
Formatted cells in `ztable` lose text formatting. 

### ISSUE THREAD

**Issue by Alex-Muirhead** [Mc-Zen/zero#9]
When applying formatting to cells (i.e. bold weight) using a `show` rule, this formatting isn't passed through for cells that are formatted within `ztable`. In the example below, the last row is meant to have a bold weight. 

![image](https://github.com/user-attachments/assets/c4eb1e63-94d3-45df-a6c2-6831ddae2f5c)

For other modules I've written, I found this snippet to be quite useful to taking an existing `cell` and applying functions to the body and/or applying parameters to the `cell`. 

```typ
#import "@preview/t4t:0.3.2" : is, is-none

#let modify-cell(it, func: none, ..style) = {
  // Default is identity mapping
  if is-none(func) { func = { body => body } }
  
  if is.elem(table.cell, it) {
    
    // Reconstruct the modified cell
    let attrs = it.fields()
    let body = attrs.remove("body")
    // Default to individual cells overriding
    table.cell(func(body), ..style, ..attrs)
    
  } else if is.elem(text, it) or is.elem("sequence", it) {
    
    // Construct a new cell for basic text
    table.cell(func(it), ..style)
    
  } else {
    
    // Let everything else (i.e. hline & vline) pass through
    it
    
  }
}
```

**Comment by Mc-Zen** [comment]
Hmm, I will need to investigate that. Thank you for reporting.

>For other modules I've written, I found this snippet to be quite useful to taking an existing cell and applying functions to the body and/or applying parameters to the cell.

Can you explain how you use this snippet? Is it for preprocessing all `..children` before passing them on to `std.table`? 
Because, the way `zero` works is different: 
- all children (table cells) are passed straight to `std.table`
- they are then modified depending on content and column just through a `show` rule on `table.cell`. This is important because only then is the (row and mainly the) column known for all cells.

**Comment by Mc-Zen** [comment]
Okay, so I have tracked the issue and the good news is that there is a solution. 

I will explain it here for the posterity but you don't need to read it ^^

At the heart of `ztable` lies something like

```typ
#show table.cell: it => {
  if is-not-numeral(it..) { it }
  else { transform-into-aligned-number(it, ..) }
}    
#table(..children)
```
This means, that 
- the cell remains unchanged if it does not contain a number or is not in a column for which number alignment has been activated,
- and otherwise the cell is replaced with something else. Importantly, in this case, it is not a `table.cell` that is returned which is perfectly legal as I make sure that it behaves just like the cell that was there before. The reason is that otherwise I would get recursive show rules. 

Since in the second case, there is no `table.cell`, it cannot be styled with `set` and `show` rules. 

Now interestingly, with the current design of the package I can somehow wrap the content into a `table.cell` without getting a recursive show rule after all.... not exactly sure why. 

But it works and now things like 
```typ
#show table.cell.where(y: 4): strong
```
behave as they should.

**Comment by Alex-Muirhead** [comment]
Fantastic, thank you for the fix and the explanation!
In regards to the snippet, yes it's used to preprocessing `..children` or a subset thereof. I can see now how `zero` relies on a bit more context.

**Comment by Alex-Muirhead** [comment]
Interestingly this doesn't work with the 0.12 release that's on the online editor. I'll give it another go offline when I get a change, with the `master` version.

**Comment by Mc-Zen** [comment]
> Interestingly this doesn't work with the 0.12 release that's on the online editor.

Can you specify what "this" is which does not work? I did not understand 😅

**Comment by Mc-Zen** [comment]
Taking a guess:

It seems that making the numbers bold does not work in the web app. But this is a different issue, not connected to zero at all.

Using strong with equations just does nothing
```typ
#strong[$12a^2+b$]
```
I wonder why since it works with tinymist ....

Try ` #show table.cell.where(y: 1): text.with(blue)`, this works fine.

**Comment by Alex-Muirhead** [comment]
Ah, whoops, yes that's the cause!
I was also using a label to add formatting to table headers and footers, which was being lost, but that feels like more of a usage issue.
